theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: "Leuck Family Reunion"
description: "Frank P Leuck and Judith Sherwood Leuck reunion site and blog."
gitorg: "https://github.com/jm1021/leuck_reunion"
description: "June 26 to July 1 2023"
google_analytics:
